name: PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    name: Run PR Agent
    steps:
      - name: PR Agent action
        uses: docker://pragent/pr-agent:latest  # new namespace as of v0.34.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GROQ__KEY: ${{ secrets.GROQ_API_KEY }}
